baseUrl: "https://blog.aminebabouri.online/"
languageCode: "en"
theme: terminal
paginate: 5
disqusShortname: https-blog-aminebabouri-online
params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 6
  # show selector to switch language
  showLanguageSelector: true
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: true
  # indicate if the homepage content should be framed
  framed: true

languages:
  en:
    languageName: English
    title: Blog - Amine Babouri
    subtitle: Your site subtitle
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: amine@blog:~/
        logoHomeLink: /

    menu:
      main:
      - identifier: cv
        name: ./cv
        url: /cv
      - identifier: posts
        name: ./posts
        url: /posts
      - identifier: tags
        name: ./tags
        url: /tags

  fr:
    languageName: Français
    title: Blog - Amine Babouri
    subtitle: Sous-titre de votre site
    keywords: ''
    menuMore: Afficher plus
    readMore: Lire la suite
    readOtherPosts: Lire les autres articles

    params:
      contentTypeName: posts-fr
      logo:
        logoText: amine@blog-fr:~/$
        logoHomeLink: /

    menu:
      main:
      - identifier: cv-fr
        name: ./cv
        url: /cv-fr
      - identifier: posts-fr
        name: ./posts-fr
        url: /fr/posts-fr
      - identifier: tags
        name: ./tags
        url: /fr/tags


